### ISSUE TITLE
Course Registration UI

### ISSUE THREAD

**Issue by donne495** [princessmittens/SEGroupProject#2]
As a developer, I want to make a course registration UI that displays all available courses  so the user can browse through them. (7 hours)

**Comment by donne495** [comment]
AT: 2.1
Given the app is in testing mode, when the course registration page is displayed, the app shows the list of courses we stored.

**Comment by donne495** [comment]
Task 1: Create activity with a list view on it and populate that list view with data

**Comment by donne495** [comment]
Task 2: Add a dropdown menu ("spinner") that will allow the user to sort the items displayed in the list by course

**Comment by reidm2** [comment]
AT: 2.2

**Comment by reidm2** [comment]
Task 1: Add a dropdown menu ("spinner") that will display a list of the faculties offering courses

**Comment by reidm2** [comment]
Task 2: Sort list of all courses when the user selects a category from the dropdown menu.
