### ISSUE TITLE
Log user registration in database

### ISSUE THREAD

**Issue by donne495** [princessmittens/SEGroupProject#46]
As a user, I want my username and info to be stored in the database so that I can have an account that keeps track of my personal registration status.

(12 hours)

**Comment by simonphilip42** [comment]
This will involve pushing a User to the Database on Registration, and pulling on login. It's been partially started, when a user registers (Or logs in) I believe, a Singleton user is created in the User class to be used as the copy of the user in the database. The push/pull is not created for this functionality yet.
