### ISSUE TITLE
Persistent_data

### ISSUE THREAD

**Issue by donne495** [princessmittens/SEGroupProject#7]
As a developer, I want to ensure that users' registration information gets permanently saved when they enter it so that their changes will still be there even if they log out. (9 hours)

**Comment by simonphilip42** [comment]
Added a User template to the Real-time database, w/ rules which prevent read/write being logged in as that specific user. Next to add the functionality within Android project

**Comment by simonphilip42** [comment]
Started a Database interface for firebase, having some trouble testing it:
The realtime database doesn't support synchronous requests well, and beyond that, requires a full application context to initialize, making normal jUnit testing difficult. We'll keep at it.
