### ISSUE TITLE
Generate Dataset

### ISSUE THREAD

**Issue by donne495** [princessmittens/SEGroupProject#9]
As a developer, I want to have a dataset to work with so that I will be able to provide a list of courses to the user. (7 hours)

**Comment by simonphilip42** [comment]
There is now a (hopefully) final dataset of courses and listings.

Courses{
Course Code : XXXX ####
Cross Listing : A course that was listed as a cross-listing, if there is one
Cross Listing URL : URL for the cross-listed course
DescriptionURL : URL of web page w/ course description & prereqs
Name : Full name, Course Code followed by given name
Semester : [FALL, WINTER] [#/XY] : DATES
Key : $CourseCode$ + $Semester$
}
Listings{
CRN : #####
Credit Hours : #
Days : Any subset of MTWRF
Instructor : Teacher(s) of course
Location : Where the course is held, multiple places if listed
Max Enrollment : #### OR a list of Faculties and ####
Time : Time of day
Key : $CourseCode$ + $Semester$
}


Still to be done, grabbing course prerequisites & descriptions.

**Comment by simonphilip42** [comment]
Added a user data-type, storing:
UID (Generated by firebase)
courses_Registered[]
courses_Completed[]

Also added Specification objects to each data type, so that a blank object can be requested to provide a slate for creation.

**Comment by simonphilip42** [comment]
User also has a Identifier parameter.
